services:
  - type: web
    name: voter-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGO_CONNECTION_STRING
        sync: false
      - key: MONGO_PASSWORD
        sync: false
      - key: MONGO_DB
        value: voter_db
